# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Gearman-Client
version:      0.02
version_from: lib/POE/Component/Gearman/Client.pm
installdirs:  site
requires:
    Gearman::Task:                 0
    List::Util:                    0
    POE:                           0
    POE::Component::Client::TCP:   0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
